baseURL = 'https://seiken-lab.com/'
languageCode = 'ja'
# paginate = 5
pygmentsUseClasses = true
title = 'Seiken Lab.'

[module]
[[module.imports]]
path = 'github.com/adityatelange/hugo-PaperMod'

[markup]
[markup.highlight]
noClasses = false

[menu]

[[menu.main]]
identifier = 'products'
name = 'products'
url = '/products/'
weight = 10

[[menu.main]]
identifier = 'blog'
name = 'blog'
url = '/blog/'
weight = 20

[[menu.main]]
identifier = 'categories'
name = 'categories'
url = '/categories/'
weight = 30

[[menu.main]]
identifier = 'tags'
name = 'tags'
url = '/tags/'
weight = 40

[minify]
disableXML = true
minifyOutput = true

[params]
DateFormat = 'January 2, 2006'
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowPostNavLinks = true
ShowReadingTime = false
ShowRssButtonInSectionTermList = false
ShowShareButtons = true
ShowWordCount = false
UseHugoToc = true
# author = 'Me'
comments = false
defaultTheme = 'auto'
description = 'Seiken Laboratory is a website about programming, technology, and more.'
disableScrollToTop = true
disableSpecial1stPost = false
disableThemeToggle = false
env = 'production'
# hideSummary = true
hidemeta = true
# images = ['<link or path of image for opengraph, twitter-cards>']
# keywords = ['Blog', 'Portfolio', 'PaperMod']
showtoc = false
title = 'Seiken Lab.'
tocopen = false

# [params.analytics]
# [params.analytics.bing]
# SiteVerificationTag = 'XYZabc'

# [params.analytics.google]
# SiteVerificationTag = 'XYZabc'

# [params.analytics.yandex]
# SiteVerificationTag = 'XYZabc'

# [params.assets]
# apple_touch_icon = '<link / abs url>'
# favicon = '<link / abs url>'
# favicon16x16 = '<link / abs url>'
# favicon32x32 = '<link / abs url>'
# safari_pinned_tab = '<link / abs url>'

# [params.cover]
# hidden = true
# hiddenInList = true
# hiddenInSingle = true

[params.editPost]
Text = 'Suggest Changes'
URL = 'https://github.com/<path_to_repo>/content'
appendFilePath = true

[params.fuseOpts]
distance = 1000
isCaseSensitive = false
keys = ['title', 'permalink', 'summary', 'content']
limit = 10
location = 0
minMatchCharLength = 0
shouldSort = true
threshold = 0.4

[params.homeInfoParams]
Content = """
Seikenãƒ©ãƒœã®ãƒšãƒ¼ã‚¸ã¸ã‚ˆã†ã“ãï¼
ã“ã®ã‚µã‚¤ãƒˆã§ã¯ã€Seikenãƒ©ãƒœã®æ´»å‹•ã‚„åˆ¶ä½œã—ã¦ã„ã‚‹ãƒ‡ãƒã‚¤ã‚¹ã‚„ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã«ã¤ã„ã¦ã®æƒ…å ±ã‚’ç™ºä¿¡ã—ã¦ã„ã¾ã™ã€‚
"""
Title = 'ã‚ˆã†ã“ã ğŸ‘‹'

# [params.label]
# icon = '/apple-touch-icon.png'
# iconHeight = 35
# text = 'Home'

# [params.profileMode]
# enabled = false
# imageHeight = 120
# imageTitle = 'my image'
# imageUrl = '<img location>'
# imageWidth = 120
# subtitle = 'This is subtitle'
# title = 'ExampleSite'

# [[params.profileMode.buttons]]
# name = 'Posts'
# url = 'posts'

# [[params.profileMode.buttons]]
# name = 'Tags'
# url = 'tags'

# [[params.socialIcons]]
# name = 'x'
# url = 'https://x.com/'

# [[params.socialIcons]]
# name = 'stackoverflow'
# url = 'https://stackoverflow.com'

# [[params.socialIcons]]
# name = 'github'
# url = 'https://github.com/'
